name: Schoolof42
favicon: null
layout_spectrum: 0.00451
typography_spectrum: 0
title: School of 42
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030303'
    - '#ffffff'
    - '#2d3e4e'
    - '#78796d'
    - '#aba693'
  brandStrength: 0
  lightness: 0.125
  saturation: 0.3435227235313505
  rhythmicContrast: 0.25
purpose: []
