name: Schoolof42
favicon: null
layout_spectrum: 0.00451
typography_spectrum: 0
title: School of 42
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3f4851'
    - '#d1cebf'
    - '#b1ab9f'
    - '#666867'
    - '#8a8a82'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
